desc: debug

train:
  seed: 42
  num_epochs: 500
  lr: 0.001
  patience: 250
  save_folder: './results/'
  device: 'cuda:0'
  log_interval: 10
  pretrained_path: Null


model:
  input_dim: 70
  hidden_dim: 64
  num_energies: 24
  num_heads: 8
  num_layers: 2
  dropout: 0.2
  return_repr: True
  add_pos_enc: False

data:
  name: 'viscosity_mixture'
  additional_features: []
  batch_size: 256
  train_ratio: 0.8
  replace: False
  logarithm: True
  label_col: 'viscosity'
  split_by: 'entry'